### ISSUE TITLE
Fail to build manylinux1 wheels

### ISSUE THREAD

**Issue by t20100** [silx-kit/hdf5plugin#108]
There is an issue building `manylinux1` wheels with current master.
Compilation of `cblosc` fails:
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_LZ4=1 -DHAVE_ZLIB=1 -DHAVE_ZSTD=1 -DH5_USE_18_API -DH5_USE_18_API -DSHUFFLE_SSE2_ENABLED=1 -Isrc/hdf5/include -Isrc/hdf5/include/linux -Isrc/c-blosc/ -Isrc/c-blosc/blosc -Isrc/c-blosc/internal-complibs/lz4-1.9.2 -Isrc/c-blosc/internal-complibs/zlib-1.2.8 -Isrc/c-blosc/internal-complibs/zstd-1.4.5 -Isrc/c-blosc/internal-complibs/zstd-1.4.5/common -Isrc/hdf5-blosc/src/ -I/opt/python/cp37-cp37m/include/python3.7m -c src/c-blosc/blosc/blosclz.c -o build/temp.linux-x86_64-3.7/src/c-blosc/blosc/blosclz.o -msse2
src/c-blosc/blosc/blosclz.c: In function ‘get_csize’:
src/c-blosc/blosc/blosclz.c:409:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (unsigned i = 0; i < (1U << HASH_LOG); i++) {
   ^
src/c-blosc/blosc/blosclz.c:409:3: note: use option -std=c99 or -std=gnu99 to compile your code
src/c-blosc/blosc/blosclz.c: In function ‘blosclz_compress’:
src/c-blosc/blosc/blosclz.c:534:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (unsigned i = 0; i < (1U << hashlog); i++) {
   ^
src/c-blosc/blosc/blosclz.c:643:47: warning: signed and unsigned type in conditional expression [-Wsign-compare]
     unsigned minlen = (clevel == 9) ? ipshift : minlen_[clevel];
                                               ^
error: command 'gcc' failed with exit status 1
```

Full log: https://gitlab.esrf.fr/silx/bob/hdf5plugin/-/jobs/174560

**Comment by vasole** [comment]
The message is fairly clear:

use option -std=c99

I guess that is preferable to patching the blosc code to move the initialization of the loop variable somewhere else.

**Comment by t20100** [comment]
Yes, see #109.

**Comment by vasole** [comment]
Should we give up manylinux1?

**Comment by t20100** [comment]
`-std=gnu99` seems to work (tested on linux and macos, not yet on `manylinux1`).

I wouldn't mind dropping `manylinux1` except for the minimum required `pip` version:

From https://github.com/pypa/manylinux:
manylinux tag | Client-side pip version required
-- | --
manylinux2014 | pip >= 19.3
manylinux2010 | pip >= 19.0
manylinux1 | pip >= 8.1.0

and [pip 19.0](https://pypi.org/project/pip/19.0/) was released on Jan 22, 2019.
So we request a 2 years old `pip` version, do you think it is OK?

**Comment by vasole** [comment]
I thought the use of the flag would introduce problems with the windows or Mac builds but it does not seem to be the case.

If we run into troubles because of supporting manylinux1, we'll drop it. It is straightforward to upgrade pip using pip.
