### ISSUE TITLE
Add pyproject.toml

### ISSUE THREAD

**Issue by t20100** [silx-kit/hdf5plugin#131]
The currently recommended python packaging way is to provide a `pyproject.toml` (PEP 517 and PEP518)... and I guess not having it will stop to work at some point.

But when adding `pyproject.toml`, build options does not work any longer, only env. var. are working.

**Comment by t20100** [comment]
Since adding `pyproject.toml` prevent using build options and using those through pip is already cumbersome (e.g., `pip install hdf5plugin --global-option=build --global-option="--openmp=False"`), what about deprecating the command line build options in favor of environment variables?

I'm really not a fan of using env. var. for this but it seems the way to do it to support recent python packaging (e.g., it's how h5py is handling it).

**Comment by vasole** [comment]
> Since adding pyproject.toml prevent using build options and using those through pip is already cumbersome (e.g., pip install 
> hdf5plugin --global-option=build --global-option="--openmp=False"), what about deprecating the command line build options > in favor of environment variables?

I'm in favor of keeping them. I find simpler to document. (Almost) Every user is able to type a command line but some of them have no clue about setting environment variables.

**Comment by t20100** [comment]
> I find simpler to document. (Almost) Every user is able to type a command line but some of them have no clue about setting environment variables.

I completely agree!...
Unfortunately, it is already hard to use with `pip` (who can guess this: `pip install hdf5plugin --global-option=build --global-option="--openmp=False"`) and impossible with PEP517 which is the currently recommended way of handling things (so I expect the legacy way to be broken sooner or later).

Anyway, we can wait and see how it evolves.

**Comment by t20100** [comment]
With current and upcoming changes in Python build/distribution, we'd better not wait too long before using `pyproject.toml` to stay in the mainstream distribution way.
