### ISSUE TITLE
Update H5Zlz4.c

### ISSUE THREAD

**Issue by mkitti** [silx-kit/hdf5plugin#158]
The H5Zlz4.c in this repository has a few issues that have been resolved here:

https://github.com/nexusformat/HDF5-External-Filter-Plugins/blob/master/LZ4/src/H5Zlz4.c

In particular:
* Fix filter not compressing with LZ4 version>1.3.0
    * https://github.com/nexusformat/HDF5-External-Filter-Plugins/commit/d48f96064cb6e229ede4bf5e5c0e1935cf691036#diff-5bbc145a3b14bd0892bda69fbbc14c5c1de507209ec680df323dde685fcffb54
* Use H5allocate_memory() and H5free() rather than malloc() and free() …
    * https://github.com/nexusformat/HDF5-External-Filter-Plugins/commit/1e1cb31afa3b9778ff9a3715a01f969f5ffad3a9#diff-5bbc145a3b14bd0892bda69fbbc14c5c1de507209ec680df323dde685fcffb54

**Comment by t20100** [comment]
I've asked upstream to tag a version on their repo to have a clear reference: https://github.com/nexusformat/HDF5-External-Filter-Plugins/issues/19 .
I'll update and pin a commit rather than a release tag if none is set.
