### ISSUE TITLE
Arm support

### ISSUE THREAD

**Issue by bamartin-ua** [silx-kit/hdf5plugin#16]
Is there any chance for ARM/ARM64 support?

**Comment by vasole** [comment]
We have a couple of Raspberry PI around but as far as I know there is no "manylinux" equivalent for ARM.

**Comment by kif** [comment]
On Fri, 03 Aug 2018 17:38:31 -0700
Benjamin Martin <notifications@github.com> wrote:

> Is there any chance for ARM/ARM64 support? 

If there is actually a need for it, we have the computer to do the build if needed.

Which processor are you targeting ?

**Comment by bamartin-ua** [comment]
I'm personally trying to run on the rockchip OP1 processor, which `uname -m` identifies as `aarch64` but I feel like that's missing some of the point, is there any way to make hdf5plugin compile on the client if it can't find a suitable pre-compiled version?

**Comment by kif** [comment]
On Tue, 04 Sep 2018 09:33:48 -0700
Benjamin Martin <notifications@github.com> wrote:

> I'm personally trying to run on the rockchip OP1 processor, which `uname -m` identifies as `aarch64` but I feel like that's missing some of the point, is there any way to make hdf5plugin compile on the client if it can't find a suitable pre-compiled version?

The OP1 has 2xA72 and 4xA53 cores. Compiling for the A53 is rather easy
as I have access to raspberry pi and pine64 boards but none with  A72 cores.

By the way, how reactive is it ? is it usable as desktop computer ?

Cheers, 

Jerome

**Comment by t20100** [comment]
With PR #18 being merged in master, `hdf5plugin` no longer embeds pre-built DLLs but instead build the filters from source with `python setup.py build`.
I haven't tested on ARM, but it should be possible to build it there now.
The possible issue is the embedded `H5pubconf.h` header file from HDF5 which is platform dependent.

**Comment by kif** [comment]
On Thu, 03 Oct 2019 08:38:14 -0700
Thomas VINCENT <notifications@github.com> wrote:

> With PR #18 being merged in master, `hdf5plugin` no longer embeds pre-built DLLs but instead build the filters from source with `python setup.py build`.
> I haven't tested on ARM, but it should be possible to build it there now.
> The possible issue is the embedded `H5pubconf.h` header file from HDF5 which is platform dependent.

We have an operational board in the office if needed...

**Comment by kif** [comment]
@bamartin-ua 
You can find a build in http://www.silx.org/pub/wheelhouse_arm64/
All tests have been passing.
Give it a chance. It was built on debian10 ... if our libc are compatible it could work.

**Comment by t20100** [comment]
@kif, thanks for the test!

**Comment by vasole** [comment]
Can this be closed? It is enough to specify where the HDF5 library is located to get the desired support.

The alternative is to provide the H5pubconf.h file used by @kif

**Comment by kif** [comment]
The latest version builds out of the box on ARM and AARM64.

**Comment by phsyron** [comment]
> By the way, how reactive is it ? is it usable as desktop computer ? Cheers, Jerome

depends on your use. mine's in a chromebook and it's really snappy for what i need it for. takes a while to do any *real* work of course (which is why I need hdf5plugin, because gz compression is *so slow*). runs forever on battery though. 

Thanks for all your help!
