### ISSUE TITLE
Unable to create dataset (error during user callback)

### ISSUE THREAD

**Issue by texadactyl** [silx-kit/hdf5plugin#161]
The following traceback is not very useful for diagnosis (sorry to complain):
```
  File "/home/elkins/tryh5.py", line 17, in <module>
    dset = h5.create_dataset("data",

  File "/home/elkins/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 149, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)

  File "/home/elkins/.local/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 142, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl)

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py/h5d.pyx", line 87, in h5py.h5d.create

ValueError: Unable to create dataset (error during user callback)
```

By "user callback", do you mean something going on between libhdf5 and the bitshuffle filter?  It would be helpful to see the nature of that "error" and where it is originating.

Source code
-----------------
```
import hdf5plugin
import h5py
import numpy as np

flag_bitshuffle = False


with h5py.File("xx.h5", "w") as h5:

    h5.attrs["CLASS"] = "FILTERBANK"
    h5.attrs["VERSION"] = "1.0"

    dout_shape     = (1, 1, 65536)  
    dout_chunk_dim = (1, 1, 512)

    if flag_bitshuffle:
        bs_compression = hdf5plugin.Bitshuffle(nelems=0, lz4=True)["compression"]
        bs_compression_opts = hdf5plugin.Bitshuffle(nelems=0, lz4=True)["compression_opts"]
        dset = h5.create_dataset("data",
                                 shape=tuple(dout_shape),
                                 chunks=tuple(dout_chunk_dim),
                                 compression=bs_compression,
                                 compression_opts=bs_compression_opts,
                                 dtype=np.float32)
    else:
        dset = h5.create_dataset("data",
                                 shape=tuple(dout_shape),
                                 chunks=tuple(dout_chunk_dim),
                                 dtype=np.float32)

    dset.dims[2].label = b"frequency"
    dset.dims[1].label = b"feed_id"
    dset.dims[0].label = b"time"

    for j in range(65536):
        dset[0, 0, j] = j

```

Software versions
------------------------
```
h5py                          3.6.0
hdf5plugin                    3.2.0
libhdf5-dev           1.10.4+repack-11ubuntu1 (Ubuntu 20.4.3 up to date)
```

My C programs are running fine with libhdf5-dev 10.4 using the bitshuffle plugin provided by hdf5plugin.  When something goes wrong, at least I can see error messages from libhdf5.

Any advice for diagnosing will be appreciated.

**Comment by vasole** [comment]
I have tested your code under Python 3.10, h5py 3.6.0,  and (sorry) HDF5 1.12.1 and windows without any problem. The file size in one case is 280.832 bytes and 38.559 in the other one.

What is the output of `h5py.version.hdf5_version` just in case something is going on there?

**Comment by vasole** [comment]
No problem with Python 3.8 and h5py 3.6.0 either (still same HDF5 library and windows OS)

**Comment by vasole** [comment]
Please, can you try to run the documentation example? I do not expect much difference but perhaps it gives us some hint.

``` python
f = h5py.File('test.h5', 'w')
f.create_dataset(
    'bitshuffle_with_lz4',
    data=numpy.arange(100),
    **hdf5plugin.Bitshuffle(nelems=0, lz4=True))
f.close()
```

**Comment by texadactyl** [comment]
@vasole
Thank you for your replies.  
>>> h5py.version.hdf5_version
'1.12.1'

I worked around whatever was the root cause by nuking all of my pip installed packages and purging the pip cache.  I am back to sanity.

The substance of this issue report is the lack of information provided when something goes wrong.  The stack trace provides no clues to the "victim".  (-:  Anything that you or the other hdf5plugin developers could do to improve trouble-shooting will be greatly appreciated.

**Comment by vasole** [comment]
To my understanding the error is caught by h5py and as far as I know their policy is to report what HDF5 reports.

**Comment by texadactyl** [comment]
As you can see from the console output, nothing helpful was reported.  Messages from libhdf5 would be welcome.

**Comment by t20100** [comment]
I confirm what @vasole said, errors reported by `h5py` are those from `libhdf5`, which are not always meaningful. You can report this to libhdf5, there is not much we can do at `hdf5plugin` level.

BTW, to turn on libhdf5 logs from `h5py`, you can use [h5py._errors.unsilence_errors](https://github.com/h5py/h5py/blob/aa31f03bef99e5807d1d6381e36233325d944279/h5py/_errors.pyx#L181).

**Comment by texadactyl** [comment]
@t20100 
IMO, a user should not have to turn on error reporting from any level.  
Anyways, I'll see what package h5py has to say with another example.
