### ISSUE TITLE
Aggression argument for Zstd aggression

### ISSUE THREAD

**Issue by mkitti** [silx-kit/hdf5plugin#163]
The Zstd plugin accepts an aggression argument. However `hdf5plugin.Zstd()` takes no arguments.

This can be worked around by providing `compression=hdf5plugin.ZSTD_ID, compression_opts=aggression` to `h5py.create_dataset`.

https://github.com/silx-kit/hdf5plugin/blob/505aad89a5d79bac20174869fc7c5959694355fd/src/HDF5Plugin-Zstandard/zstd_h5plugin.c#L35

**Comment by t20100** [comment]
Indeed, that's missing!
Thanks for the report.

Pull request welcomed!

**Comment by mkitti** [comment]
I implemented thr argument in #164
