### ISSUE TITLE
Request: Please add to Anaconda

### ISSUE THREAD

**Issue by texadactyl** [silx-kit/hdf5plugin#17]
I noticed that ```silx``` is in conda-forge.  Please: 
(1) Add ```hdf5plugin``` to either default or conda-forge.
(2) Document this in README.md.

Thank you.

**Comment by vasole** [comment]
We do not consider hdf5plugin a hard dependency of silx and ``pip install hdf5plugin`` should also work for conda.  Is using pip a problem?

**Comment by vasole** [comment]
Current master allows to build the package in a pure anaconda environment (with conda install gcc) as well as to use the wheels from pip.

**Comment by t20100** [comment]
FYI, hdf5plugin has just been added to conda-forge: https://anaconda.org/conda-forge/hdf5plugin
