### ISSUE TITLE
Remove unused code from the compression filters

### ISSUE THREAD

**Issue by t20100** [silx-kit/hdf5plugin#222]
As the number of embedded filters increases, so is the number of unused files in the project.
What about stripping the copied source to only keep what is needed?

That's probably going to make the update of embedded projects a bit more complicated, but that would also make clearer what is actually used and reduce the number of files in the repo and in release tarballs.

**Comment by vasole** [comment]
I find more disadvantages than advantages by doing so.

Shipping the original repository as it was allows to rebuild the original project and **test** if there was an issue in the original code. If we remove the added examples, test code and original build-mechanism to reduce disk space, I do not think we are gaining with the change.

**Comment by t20100** [comment]
OK, I didn't considered this, let's keep it as it is then.

**Comment by t20100** [comment]
BTW, we could consider stripping things when generating the `sdist` tarball and have CI tests checking the build from `sdist`, so we both have access to original project for development and reduced tarball.
