### ISSUE TITLE
Add license conditions of used filters.

### ISSUE THREAD

**Issue by vasole** [silx-kit/hdf5plugin#3]
Some of the used filters ask the license/copyright to be distributed with the binary files.

**Comment by vasole** [comment]
@kif @t20100 

The LZ4 library used with bitshuffle contains the following paragraph:

* Redistributions in binary form must reproduce the above copyright notice, this
  list of conditions and the following disclaimer in the documentation and/or
  other materials provided with the distribution

What is the correct way to proceed? 

- A file containing all the licenses?
- A file for each dll with the license?
- A way to retrieve the license from the module?
- ...

**Comment by t20100** [comment]
I don't know the correct way, but I'd include a license file in the package, and point to it from the README...

**Comment by vasole** [comment]
If I take a look at other packages, it seems the "copyright" file seems to be the most complete solution.

**Comment by vasole** [comment]
The copyright approach is overkill in this case. Since it is very unlikely that this becomes a Debian package, I think adding a copy of the original license for each of the plugins is adequate.

**Comment by vasole** [comment]
Closed by #7
