### ISSUE TITLE
Change helper API to prepare for better integration with h5py 3.0

### ISSUE THREAD

**Issue by t20100** [silx-kit/hdf5plugin#40]
Initially proposed here https://github.com/h5py/h5py/issues/1315#issuecomment-540017728 by @takluyver:
```
f.create_dataset('blosc_byte_shuffle_blosclz', data=numpy.arange(100),
    compression=hdf5plugin.Blosc(level=9, shuffle='byte'))

# Instead of
f.create_dataset('blosc_byte_shuffle_blosclz', data=numpy.arange(100),
    **hdf5plugin.blosc_options(level=9, shuffle='byte', compression='blosclz'))
```

Basically turn `*_options` helpers to classes which can be provided as the `compression` argument of `create_dataset` with h5py 3.x... and still can be used as `**kwargs` for h5py v2.x

**Comment by t20100** [comment]
Basically something like zarr/numcodec API (https://zarr.readthedocs.io/en/stable/api/codecs.html#module-zarr.codecs)

**Comment by vasole** [comment]
Shouldn't we wait until h5py defines what is to be provided?

**Comment by takluyver** [comment]
I'll  try to draft something now - as hdf5plugin would probably be the main user of this, your input is very welcome!

**Comment by takluyver** [comment]
Take a look at https://github.com/h5py/h5py/pull/1389
