### ISSUE TITLE
MacOS wheels do not work on Yosemite or El Capitan

### ISSUE THREAD

**Issue by vasole** [silx-kit/hdf5plugin#59]
The Python 3.6 wheels do not work on Yosemite or El Capitan machines.

Are you sure we are setting the MACOSX_DEPLOYMENT_TARGET to something acceptable?

Building the wheels on those machines works.

**Comment by t20100** [comment]
Wheels were generated on a macos 10.12 computer without setting `MACOSX_DEPLOYMENT_TARGET`.
Build chain has been updated to build with `MACOSX_DEPLOYMENT_TARGET=10.9`
