### ISSUE TITLE
Can't read file compressed with FCIDECOMP

### ISSUE THREAD

**Issue by mraspaud** [silx-kit/hdf5plugin#69]
This is a follow up of https://github.com/h5py/h5py/issues/1537 somehow.

I just installed @vasole 's wheel: http://ftp.esrf.fr/pub/bliss/hdf5plugin-2.1.3a0-py2.py3-none-linux_x86_64.whl with pip, but still get an error when reading a sample compressed file:

```python
❯ python
Python 3.8.2 | packaged by conda-forge | (default, Mar 23 2020, 18:16:37) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> h5f = h5py.File('/home/a001673/usr/contrib/FCIDECOMP_V1.0.1/Software/FCIDECOMP_SOURCES/fcidecomp-test/data/sample.nc', mode='r')
>>> h5f["effective_radiance"]
<HDF5 dataset "effective_radiance": shape (60, 30), type "<i2">
>>> h5f["effective_radiance"][:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/a001673/miniconda3/envs/py3/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 182, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't open directory: /home/a001673/miniconda3/envs/py3/lib/hdf5/plugin)
```
As you can see, this is running in conda environment, with python 3.8. 

Any more details I can provide ?

**Comment by t20100** [comment]
You need to `import hdf5plugin` first (before or after `h5py`), but before using the filter.

**Comment by vasole** [comment]
You also have to make sure your FCIDECOMP plugin is not already in your HDF5_PLUGIN_PATH. Our module is very conservative and if it finds the user has already registered the plugin via the environmental variable, the plugin is not registered in order to respect user's choice.

**Comment by mraspaud** [comment]
Still no luck, even when importing hdf5plugin:
```
>>> import h5py
>>> import hdfplugin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'hdfplugin'
>>> import hdf5plugin
>>> h5f = h5py.File('/home/a001673/usr/contrib/FCIDECOMP_V1.0.1/Software/FCIDECOMP_SOURCES/fcidecomp-test/data/sample.nc', mode='r')
>>> h5f["effective_radiance"][:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/a001673/miniconda3/envs/py3/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 182, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't open directory: /home/a001673/miniconda3/envs/py3/lib/hdf5/plugin)
>>> 
❯ echo $HDF5_PLUGIN_PATH
(empty variable)
```

**Comment by t20100** [comment]
I can reproduce it with the same file.

**Comment by vasole** [comment]
That file and the one used in the unit tests are supposed to be the same.

**Comment by t20100** [comment]
The filter ID of the `sample.nc` is 56782 which is user-defined ID. The official one for the fcidecomp filter is 32018.

**Comment by t20100** [comment]
See: https://github.com/silx-kit/hdf5plugin/blob/master/src/fcidecomp/FCIDECOMP_V1.0.1/Software/FCIDECOMP_SOURCES/fcicomp-H5Zjpegls/include/H5Zjpegls.h#L24 and https://github.com/silx-kit/hdf5plugin/blob/master/src/fcidecomp/FCIDECOMP_V1.0.1/Software/FCIDECOMP_SOURCES/fcicomp-H5Zjpegls/src/H5Zjpegls.c#L31

**Comment by t20100** [comment]
So the `FCIDECOMP_V1.0.1/Software/FCIDECOMP_SOURCES/fcidecomp-test/data/sample.nc` file is using a filter ID that is not the official one....

**Comment by t20100** [comment]
BTW, to get the filter ID of a dataset:
```
In [3]: f["effective_radiance"]._filters                                        
Out[3]: {'56782': (2, 1, 60, 30, 16, 1, 0, 0, 0, 0, 0, 0, 0)}
```

**Comment by vasole** [comment]
The same file from the 1.0.2 version of the sources uses the proper filter and works perfectly.

ftp://ftp.eumetsat.int/pub/OPS/out/test-data/Test-data-for-External-Users/MTG_FCI_Test-Data/FCI_Decompression_Software_V1.0.2/

**Comment by vasole** [comment]
@mraspaud 

The file you are trying to read is not the same you provided in h5py/h5py#1537

**Comment by t20100** [comment]
They probably moved from an unofficial ID to a registered one in between...
Are those 2 versions are compatible?

**Comment by vasole** [comment]
The test file is.

**Comment by t20100** [comment]
OK, good.

**Comment by vasole** [comment]
I will upgrade their sources. They changed the filter ID and they look more robust.

**Comment by t20100** [comment]
OK sounds good!

**Comment by t20100** [comment]
Funny that the hdf5 filter registry (https://support.hdfgroup.org/services/filters.html) is not pointing to the version with the official ID...

**Comment by mraspaud** [comment]
thanks, let me try the sample.nc of v1.0.2

**Comment by mraspaud** [comment]
No luck with the other one either:
```>>> import h5py
>>> h5f = h5py.File('/home/a001673/Downloads/EUMETSAT-FCIDECOMP_V1.0.2/FCIDECOMP_V1.0.2/Software/fcidecomp_sources-V1.0.2/FCIDECOMP_SOURCES/fcidecomp-test/data/sample.nc', mode='r')
>>> h5f['effective_radiance'][:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/a001673/miniconda3/envs/pyprojtest/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 182, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't open directory: /home/a001673/miniconda3/envs/pyprojtest/lib/hdf5/plugin)
```

**Comment by mraspaud** [comment]
Is this still the right wheel to use ?
hdf5plugin-2.1.3a0-py2.py3-none-linux_x86_64.whl

**Comment by vasole** [comment]
I expect it to work despite being older than the current master branch.

**Comment by vasole** [comment]
You can clone out master and build it under your environment. Have you tried to read the file you posted when opening the h5py issue:

https://github.com/h5py/h5py/files/4508049/sample.zip

**Comment by mraspaud** [comment]
ok, I can try getting the master branch

**Comment by mraspaud** [comment]
yes, I used the one I provided, without luck. Let me build from master

**Comment by mraspaud** [comment]
@vasole: building and install from source did the trick ! I can now read the file correctly. Could it be that the wheel installs the plugins in the wrong place ?

**Comment by t20100** [comment]
With the wheel from http://ftp.esrf.fr/pub/bliss/hdf5plugin-2.1.3a0-py2.py3-none-linux_x86_64.whl,  I can read the `effective_radiance` dataset from https://github.com/h5py/h5py/files/4508049/sample.zip with OS debian10, with a virtualenv with python 3.7.3, h5py 2.10.0.

**Comment by t20100** [comment]
Maybe a binary incompatibility of the plugin?
I'm generating manylinux wheels, they should be available in a moment here : https://silx.gitlab-pages.esrf.fr/bob/hdf5plugin/ (check the update time at the bottom of the page!)

**Comment by vasole** [comment]
No. I think in that case you are falling on the same trap I mentioned as hint when you opened the issue. Conda uses its own compiler and when there is C++ code involved there can be nasty surprises with it.  I had modules that compiled and installed when using the system gcc but could not be run under conda unless one would do ``conda install gcc`` prior to build and install the package.

**Comment by vasole** [comment]
My precious post was addressed to @mraspaud, and not to @t20100

**Comment by vasole** [comment]
@t20100 

My wheel used CentOS 7. I guess the one generated by bob it will be a pure CentOS 5 and it will have greater chances to succeed.

**Comment by mraspaud** [comment]
Ok, so yes, the compiler could be the problem then.
Thanks a lot for your help so far!

**Comment by t20100** [comment]
For the wheels, there are 2 kinds: manylinux and manylinux2014 and only the later has c++11, so it will depends.
Anyway, once we make a new release, it will be available in conda as well.

**Comment by vasole** [comment]
@mraspaud 

Please, for our own records, can you tell us if the manylinux2014 works in your system?

https://silx.gitlab-pages.esrf.fr/bob/hdf5plugin/hdf5plugin-2.1.3a0-py2.py3-none-manylinux2014_x86_64.whl

**Comment by mraspaud** [comment]
@vasole It doesn't:
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/a001673/miniconda3/envs/pyprojtest/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 182, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't open directory: /home/a001673/miniconda3/envs/pyprojtest/lib/hdf5/plugin)
```

Installed like this:
```
❯ pip install ~/Downloads/hdf5plugin-2.1.3a0-py2.py3-none-manylinux2014_x86_64.whl
Processing /home/a001673/Downloads/hdf5plugin-2.1.3a0-py2.py3-none-manylinux2014_x86_64.whl
Requirement already satisfied: h5py in /home/a001673/miniconda3/envs/pyprojtest/lib/python3.8/site-packages (from hdf5plugin==2.1.3a0) (2.10.0)
Requirement already satisfied: numpy>=1.7 in /home/a001673/miniconda3/envs/pyprojtest/lib/python3.8/site-packages (from h5py->hdf5plugin==2.1.3a0) (1.18.1)
Requirement already satisfied: six in /home/a001673/miniconda3/envs/pyprojtest/lib/python3.8/site-packages (from h5py->hdf5plugin==2.1.3a0) (1.14.0)
Installing collected packages: hdf5plugin
Successfully installed hdf5plugin-2.1.3a0
```

**Comment by mraspaud** [comment]
Both `$HDF5_PLUGIN_PATH` and `$LD_LIBRARY_PATH` are empty by the way. The conda environment it fresh.

**Comment by mraspaud** [comment]
> Maybe a binary incompatibility of the plugin?
> I'm generating manylinux wheels, they should be available in a moment here : https://silx.gitlab-pages.esrf.fr/bob/hdf5plugin/ (check the update time at the bottom of the page!)

The page still show april 1st as las update time...

**Comment by t20100** [comment]
The builds available at https://silx.gitlab-pages.esrf.fr/bob/hdf5plugin/ are broken for now, because our Windows gitlab runner is down.

**Comment by mraspaud** [comment]
No problem, just ping me if you need me to test something, I'm glad to be of any help!

**Comment by t20100** [comment]
Build is fixed and new wheels are available: https://silx.gitlab-pages.esrf.fr/bob/hdf5plugin/
Could you test the manylinux2014 wheel (an up-to-date `pip` is needed)? The other one does not contains the FCIDECOMP plugin because it is built without C++11.

**Comment by mraspaud** [comment]
Seems to be working great! Thanks a lot !

```
❯ pip uninstall hdf5plugin
WARNING: Skipping hdf5plugin as it is not installed.
❯ pip install ~/Downloads/hdf5plugin-2.1.3a0-py2.py3-none-manylinux2014_x86_64.whl
Processing /home/a001673/Downloads/hdf5plugin-2.1.3a0-py2.py3-none-manylinux2014_x86_64.whl
Requirement already satisfied: h5py in /home/a001673/miniconda3/envs/pyprojtest/lib/python3.8/site-packages (from hdf5plugin==2.1.3a0) (2.10.0)
Requirement already satisfied: six in /home/a001673/miniconda3/envs/pyprojtest/lib/python3.8/site-packages (from h5py->hdf5plugin==2.1.3a0) (1.14.0)
Requirement already satisfied: numpy>=1.7 in /home/a001673/miniconda3/envs/pyprojtest/lib/python3.8/site-packages (from h5py->hdf5plugin==2.1.3a0) (1.18.1)
Installing collected packages: hdf5plugin
Successfully installed hdf5plugin-2.1.3a0
❯ python
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 08:20:52) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> import hdf5plugin
>>> h5f = h5py.File('/home/a001673/sample.nc', mode='r')
>>> h5f['effective_radiance'][:]
array([[   0,    1,    2, ...,   27,   28,   29],
       [  30,   31,   32, ...,   57,   58,   59],
       [  60,   61,   62, ...,   87,   88,   89],
       ...,
       [1710, 1711, 1712, ..., 1737, 1738, 1739],
       [1740, 1741, 1742, ..., 1767, 1768, 1769],
       [1770, 1771, 1772, ..., 1797, 1798, 1799]], dtype=int16)
```

**Comment by mraspaud** [comment]
@ameraner @gerritholl you might be interested in this

**Comment by t20100** [comment]
Good to hear!
We'll prepare a release soon.
