### ISSUE TITLE
FCIDECOMP Update version of the original sources

### ISSUE THREAD

**Issue by vasole** [silx-kit/hdf5plugin#70]
The test file of the 1.0.1 version uses wrong filter ID.

**Comment by t20100** [comment]
Can we move to 1.0.2?
Else I don't think it is a problem, as long as it works with the official ID.

**Comment by vasole** [comment]
I have verified. They use the official ID and the sample.nc file can be read already by the current version of hdf5plugin. They provide additional test files and the code seems more robust.
