### ISSUE TITLE
Support for zfp

### ISSUE THREAD

**Issue by hhoeflin** [silx-kit/hdf5plugin#73]
Love hdf5 plugin. Use it for blossc. What would be great it so have lossy compression available. Is there a possibility of supporting zfp.

https://github.com/LLNL/H5Z-ZFP

Thanks!

**Comment by vasole** [comment]
My zfp branch works under windows, but I cannot make it work under linux without passing the location of the hdf5 library as argument:

https://github.com/vasole/hdf5plugin/tree/zfp

@t20100 Should we envisage to include it into the repository under those conditions? The zfp filter under platforms other than windows would have to be built from source passing the location of the HDF5 library. I guess it would work for conda but we would not be able to include zfp support into our wheels.

**Comment by vasole** [comment]
@t20100 The problems come from a plethora of H5?_XXXXXX_g undefined symbols. Most of them from H5E

**Comment by t20100** [comment]
That's due to the weird understanding of constants in libhdf5.
There is already a few in `hdf5_dl.c`:
https://github.com/silx-kit/hdf5plugin/blob/master/src/hdf5_dl.c#L101
https://github.com/silx-kit/hdf5plugin/blob/master/src/hdf5_dl.c#L146
I'll have a look at it.

**Comment by t20100** [comment]
Closed by PR #74.
Related issue: #75

**Comment by hhoeflin** [comment]
Wow that was fast. Thanks so much!

**Comment by vasole** [comment]
@hhoeflin 

Release available from PyPI.
