### ISSUE TITLE
Zpf does not work for uint8 arrays.

### ISSUE THREAD

**Issue by petoor** [silx-kit/hdf5plugin#86]
Hi.

Zpf gives the error : ValueError: Unable to create dataset (invalid datatype size) when running the following code:

```
import numpy
import h5py
import hdf5plugin

# Compression
f = h5py.File('test.h5', 'w')
array = numpy.uint8(numpy.random.randint(255, size=(100, 100)))
f.create_dataset('data', data=array, **hdf5plugin.Zfp())
f.close()
```

However, changing it to numpy.uint32 works. How can this be? 
In your setup file you specify that it is build with uint8. So if i understand it correctly, it should work for uint8 but for uint32.
https://github.com/silx-kit/hdf5plugin/blob/0cb21542d5f1debc85034b64736722722faeb3ea/setup.py#L524

Best regards

**Comment by vasole** [comment]
If we take a look the the actual source code of the original filter, you can see that only 32 and 64 bit are supported

https://github.com/LLNL/H5Z-ZFP/blob/master/src/H5Zzfp.c

```
 else if (dclass == H5T_INTEGER)
    {
        if (dsize == sizeof(int32))
            zt = zfp_type_int32;
        else if (dsize == sizeof(int64))
            zt = zfp_type_int64;
        else
            H5Z_ZFP_PUSH_AND_GOTO(H5E_ARGS, H5E_BADTYPE, -1, "invalid datatype size");
    }
```

**Comment by t20100** [comment]
This flag is needed to build the ZFP library for the filter (see https://h5z-zfp.readthedocs.io/en/latest/installation.html#compiling-zfp), it does not toggle the support of uint8.

**Comment by t20100** [comment]
I'm closing it since this is a limitation from the filter itself.

Please reopen if needed.
