### ISSUE TITLE
Distribute 32-bit HDF5 binary plugins

### ISSUE THREAD

**Issue by lilastic** [silx-kit/hdf5plugin#94]
Besides 64-bit, would it be possible to distribute 32-bit HDF5 binary plugins? That would be great - thanks!

**Comment by vasole** [comment]
I see very little interest.

- Numpy and h5py only provide 32-bit versions for windows.

- Microsoft stopped providing 32-bit windows 10 versions to computer manufacturers this year.

**Comment by lilastic** [comment]
Thanks @vasole!

I understand - it's more than some of us still have to work with legacy HW and SW stacks and can't move to 64-bit.

**Comment by kif** [comment]
Then the best is that you contribute to backport hdf5plugin for your platform.

**Comment by lilastic** [comment]
Thanks @kif !

**Comment by t20100** [comment]
I'm closing it, please reopen if needed.
