### ISSUE TITLE
Missing FCIDECOMP HDF5 plugin for Linux distributions

### ISSUE THREAD

**Issue by lilastic** [silx-kit/hdf5plugin#95]

**Comment by t20100** [comment]
Which operating system and python do you use?
Which way did you install `hdf5plugin`? (from a wheel,  from source or through conda?)

For Linux, we provide 2 wheels: `manylinux1` and `manylinux2014`.
FCIDECOMP filter is only available in the manylinux2014 wheel since it requires C++11.

**Comment by t20100** [comment]
You might need an up-to-date version of `pip` to install the `manlinux2014` wheel.

**Comment by vasole** [comment]
I suspect this is related to #94 from the same poster.

**Comment by t20100** [comment]
FCIDECOMP HDF5 plugin availability depends on the availability of C++11 so it is only available in manylinux2014 wheels.
I'm closing it, please reopen if needed.
