### ISSUE TITLE
Build options at runtime ?

### ISSUE THREAD

**Issue by jonwright** [silx-kit/hdf5plugin#96]
When I import hdf5plugin is there a way to check if it was compiled for the current cpu and whether openmp is enabled?
Related, is there a plan to have these options selected at runtime ?
Thanks!

**Comment by kif** [comment]
> When I import hdf5plugin is there a way to check if it was compiled for the current cpu and whether openmp is enabled?

For OpenMP, you can check with `ldd` if the libraries (.so) are linked
to libgomp and libpthreads under linux. 

For SSE / AVX the solution I am using is to inspect the .so files with
objdump and search to the usage of xmm register (SSE) or ymm registers
(AVX). zmm is used for AVX512 but none of our code uses them yet.

Of course, this is under linux but the same exists probably under
alternative operating systems

> Related, is there a plan to have these options selected at runtime ?

I don't think so as code doing this is rather brittle and hardly
portable.

**Comment by vasole** [comment]
The code builds perfectly from source and it is not brittle at all.

You just have to compile it on your target computer.

**Comment by vasole** [comment]
Concerning the open poster, I guess it would not cost much to store the configuration used when building the module.

If what you want is the maximum performance then, as usual, you have to compile the module on the target computer as suggested in the https://github.com/silx-kit/hdf5plugin/blob/master/README.rst

**Comment by jonwright** [comment]
Storing the config into the module would be useful to try to guess whether we need to recompile it.

**Comment by kif** [comment]
> The code builds perfectly from source and it is not brittle at all.

@vasole , I meant to test at _runtime_ if a CPU feature is present or not and if it is worth using it. 
Just an example: At runtime, if an AVX instruction is used, all SSE registers needs to be dumped (regardless if it the same process or not!) which means that for some times SSE has to be (temporary) disabled !
Even more difficult: issuing a single AVX512 instruction enforces the slow-down by 400MHz of the processor, then is it worth ? 
Many advocate for not using those instructions (until this is fixed).

**Comment by jonwright** [comment]
A method to get/set the number of threads at runtime can be helpful (or at least to turn threading on or off). 

For now we want the fastest Lima/Eiger2 reader that you can supply - I am assuming this is a source install of hdf5plugin? If there is something better please let me know.

**Comment by kif** [comment]
If it is compiled with OpenMP, you can always disable it by setting the environment variable `OMP_NUM_THREADS=1`

**Comment by vasole** [comment]
> For now we want the fastest Lima/Eiger2 reader that you can supply - I am assuming this is a source install of hdf5plugin?
> If there is something better please let me know.

The faster readout would imply direct chunk reading. In other words using https://confluence.hdfgroup.org/display/HDF5/H5D_READ_CHUNK

This library just makes the filters available. The access to the direct chunk reading comes from h5py itself.

**Comment by t20100** [comment]
We can't provide multiple compilation options for selection at runtime without heavily modifying the filters.

But we can give access to the build config so users can easily retrieve it.
We can also add `OMP_NUM_THREADS=1` to the doc.
